name: Deploy Notes Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H 207.180.211.224 >> ~/.ssh/known_hosts

      - name: Update project code.
        run: |
          scp deploy.sh root@207.180.211.224:~/deploy.sh
          ssh root@207.180.211.224 'chmod +x ~/deploy.sh && ~/deploy.sh'
